disabled_rules:
- nesting
- unused_closure_parameter # are ok as documentation
- trailing_comma # allow trailing comma in multiline arrays. swiftformat even adds this.
opt_in_rules:
- empty_count
- empty_string
excluded:
- Carthage
- Pods
#- SwiftLint/Common/3rdPartyLib
- DerivedData
cyclomatic_complexity:
    warning: 20
    error: 25
variable_name:
    max_length:
        error: 45
    min_length:
        warning: 1
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
function_body_length:
    warning: 300
    error: 500
type_body_length:
    warning: 1000
    error: 1500
line_length:
    warning: 120
    ignores_function_declarations: false
    ignores_comments: true
    ignores_urls: false
force_cast:
    warning
force_try:
    warning
reporter: "xcode"
